name: MusicFindApp 
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  avatar_glow: ^2.0.2
  url_launcher: ^6.1.6
  record: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
